modLoader="javafml"
loaderVersion="[36,]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Level-Text-Fix/issues"
license="LGPL v2.1"

[[mods]]
modId="leveltextfix"
version="1.0.0"
displayName="LevelTestFix"
displayURL="https://www.curseforge.com/minecraft/mc-mods/level-text-fix"
credits="Darkhax"
authors="Darkhax"
description='''
Fixes issues with level text.
'''

[[dependencies.leveltextfix]]
modId="forge"
mandatory=true
versionRange="[36,]"
ordering="NONE"
side="CLIENT"

[[dependencies.leveltextfix]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="CLIENT"