modLoader = "javafml"
license = "LGPL 2.1"
issueTrackerURL = "https://github.com/Darkhax-Minecraft/Level-Text-Fix/issues"

[[mods]]
modId = "leveltextfix"
version = "26.1.2.0"
displayName = "LevelTextFix"
updateJSONURL = "https://updates.blamejared.com/get?n=leveltextfix&gv=26.1.2&ml=neoforge"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/level-text-fix"
logoFile = "logo_leveltextfix.png"
logoBlur = false
credits = "This project is made possible with Patreon support from players like you. Thank you! lothrazar, techsquirrel, Keyana , Darkosto, Tobias Ward, noobanidus"
authors = "Darkhax"
description = "Fix issues related to level text, and adds acessibility options."

[[mixins]]
config = "leveltextfix.common.mixins.json"

[[mixins]]
config = "leveltextfix.neoforge.mixins.json"

[[dependencies.leveltextfix]]
modId = "minecraft"
type = "required"
versionRange = "26.1"
ordering = "NONE"
side = "BOTH"

[[dependencies.leveltextfix]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.0.1-beta,)"
ordering = "NONE"
side = "BOTH"

